import {ALittleLife, ARaisinInTheSun, ADmiralYiSunSin, AfricanEuropeans, AlfieAndMe, AnneFranksDiary, Berserk,
DogManMother, FourthWing, GenghisKhan, HauntingAdeline, HelloBeautiful, Holly, ISurvived, JustEat, KnowledgeEncyclopedia,
Macbeth, MarvelEncyclopedia, Meditations, NapoleonALife, NatashasKitchen, NormalPeople, TextureOverTaste, The48Laws, TheBoatanist, TheBoy, TheExchange,
TheHausemaid, TheLastRonin, TheOdyssey, ThePictureOfDorianGrey, TheScarletLetter, TheSevenHusbandsOfEnelynHugo,
TheStoryOfDisney, TheTearsThatTaughtMe, TheWager, TheWayForward, TimedTests, ToInfinityAndBeyond,
Unruly} from "../assets";

export const Books = [
    {
        BookId: 1,
        BookName: "Anne Frank's Diary",
        Author: "Anne Frank",
        Info: "A timeless story rediscovered by each new generation, The Diary of a Young Girl stands without peer. This graphic edition remains faithful to the original, while the stunning illustrations interpret and add layers of visual meaning and immediacy to this classic work of Holocaust literature.",
        Price: 19.99,
        BookImg: AnneFranksDiary,
        Category: "Comics & Graphic Novel",
    },
    {
        BookId: 2,
        BookName: "Berserk",
        Author: "Kentaro Miura",
        Info: "Have you got the Guts? Kentaro Miura's Berserk has outraged, horrified, and delighted manga and anime fanatics since 1989, creating an international legion of hardcore devotees and inspiring a plethora of TV series, feature films, and video games.",
        Price: 12.99,
        BookImg: Berserk,
        Category: "Comics & Graphic Novel",
    },
    {
        BookId: 3,
        BookName: "Dog Man Mother",
        Author: "Dav Pilkey",
        Info: "Dog Man is down on his luck, Petey confronts his not so purr-fect past, and Grampa is up to no good. The world is spinning out of control as new villains spill into town. Everything seems dark and full of despair. But hope is not lost. Can the incredible power of love save the day?",
        Price: 7.99,
        BookImg: DogManMother,
        Category: "Comics & Graphic Novel",
    },
    {
        BookId: 4,
        BookName: "I Survived",
        Author: "Lauren Tarshis",
        Info: "Nathaniel Fox never imagined he’d find himself in the middle of a blood-soaked battlefield, fighting for his life. He’s only eleven years old! He’s barely paid attention to the troubles between America and England. Instead, he’s been worked to the bone by his cruel uncle.",
        Price: 9.99,
        BookImg: ISurvived,
        Category: "Comics & Graphic Novel",
    },
    {
        BookId: 5,
        BookName: "Marvel Encyclopedia",
        Author: "Stan Lee",
        Info: "Discover the essential facts about Marvel Comics’ timeless heroes such as Captain America, Spider-Man, and Iron Man and villains like Thanos, Loki, and Kingpin.",
        Price: 21.99,
        BookImg: MarvelEncyclopedia,
        Category: "Comics & Graphic Novel",
    },
    {
        BookId: 6,
        BookName: "The Boy, the mole, the fox and the Horse",
        Author: "Charlie Mackesy",
        Info: "From British illustrator, artist, and author Charlie Mackesy comes a journey for all ages that explores life’s universal lessons, featuring 100 color and black-and-white drawings.",
        Price: 18.99,
        BookImg: TheBoy,
        Category: "Comics & Graphic Novel",
    },
    {
        BookId: 7,
        BookName: "The Last Ronin",
        Author: "Tom Waltz",
        Info: "What terrible events destroyed his family and left New York a crumbling, post-apocalyptic nightmare? All will be revealed in this climactic Turtle tale that sees longtime friends becoming enemies and new allies emerging in the most unexpected places. Can the surviving Turtle triumph?",
        Price: 18.99,
        BookImg: TheLastRonin,
        Category: "Comics & Graphic Novel",
    },
    {
        BookId: 8,
        BookName: "The Story of Disney",
        Author: "John Baxter",
        Info: "The Walt Disney Company honors its 100th anniversary in 2023. As part of the festivities, this must-have coffee table book showcases the company's history and rich legacy―past, present, and future―through vibrant voices and rare Disney concept art and photographs.",
        Price: 29.99,
        BookImg: TheStoryOfDisney,
        Category: "Comics & Graphic Novel",
    },
    {
        BookId: 9,
        BookName: "Just Eat",
        Author: "Jessie James Decker",
        Info: "Comfort means everything to Jessie James Decker. It’s in the music she makes, the time she spends with her family, and most of all, the food she cooks. In her bestselling cookbook, Just Feed Me, Jessie James Decker brought readers into her kitchen for an exclusive taste of her homey, family-friendly recipes. Now, in Just Eat, Jessie brings comfort food to the table, inviting everyone back over for dinner at the Decker’s with her most personal and mouthwatering dishes yet.",
        Price: 20.49,
        BookImg: JustEat,
        Category: "Cookbooks",
    },
    {
        BookId: 10,
        BookName: "Natasha's Kitchen",
        Author: "Natasha Kravchuk",
        Info: "NEW YORK TIMES BESTSELLER • An inviting collection of more than 100 trusted, budget-friendly recipes for every meal and occasion from the creator of the wildly popular website Natasha’s Kitchen.",
        Price: 19.99,
        BookImg: NatashasKitchen,
        Category: "Cookbooks",
    },
    {
        BookId: 11,
        BookName: "Texture Over Taste",
        Author: "Joshua Weissman",
        Info: "NEW YORK TIMES BESTSELLER • Joshua Weissman is back with a bold and exciting new cookbook that will take your cooking to an entirely different level!",
        Price: 21.99,
        BookImg: TextureOverTaste,
        Category: "Cookbooks",
    },
    {
        BookId: 12,
        BookName: "A Raisin in the Sun",
        Author: "Lorraine Hansberry",
        Info: "'Never before, in the entire history of the American theater, has so much of the truth of Black people's lives been seen on the stage,' observed James Baldwin shortly before A Raisin in the Sun opened on Broadway in 1959.",
        Price: 18.99,
        BookImg: ARaisinInTheSun,
        Category: "Dramas & Plays",
    },
    {
        BookId: 13,
        BookName: "Hello Beautiful",
        Author: "Ann Napolitano",
        Info: "William Waters grew up in a house silenced by tragedy, where his parents could hardly bear to look at him, much less love him—so when he meets the spirited and ambitious Julia Padavano in his freshman year of college, it’s as if the world has lit up around him.",
        Price: 15.99,
        BookImg: HelloBeautiful,
        Category: "Dramas & Plays",
    },
    {
        BookId: 14,
        BookName: "Macbeth",
        Author: "William Shakespeare",
        Info: "The authoritative edition of Macbeth from The Folger Shakespeare Library, the trusted and widely used Shakespeare series for students and general readers.",
        Price: 7.99,
        BookImg: Macbeth,
        Category: "Dramas & Plays",
    },
    {
        BookId: 15,
        BookName: "Normal People",
        Author: "Sally Rooney",
        Info: "Connell and Marianne grew up in the same small town, but the similarities end there. At school, Connell is popular and well liked, while Marianne is a loner. But when the two strike up a conversation—awkward but electrifying—something life changing begins.",
        Price: 12.99,
        BookImg: NormalPeople,
        Category: "Dramas & Plays",
    },
    {
        BookId: 16,
        BookName: "The Picture of Dorain Gray",
        Author: "Oscar Wilde",
        Info: "The Picture of Dorian Gray is a 1891 gothic and philosophical novel by Irish writer and playwright Oscar Wilde. First published as a serial story in the July 1890 issue of Lippincott's Monthly Magazine, the editors feared the story was indecent, and without Wilde's knowledge, deleted five hundred words before publication.",
        Price: 7.47,
        BookImg: ThePictureOfDorianGrey,
        Category: "Dramas & Plays",
    },
    {
        BookId: 17,
        BookName: "The Scarlet Letter",
        Author: "Nathaniel Hawthorne",
        Info: "The Scarlet Letter: A Romance is a work of historical fiction by American author Nathaniel Hawthorne, published in 1850. Set in Puritan Massachusetts Bay Colony during the years 1642 to 1649, the novel tells the story of Hester Prynne, who conceives a daughter through an affair and then struggles to create a new life of repentance and dignity. Containing a number of religious and historic allusions, the book explores themes of legalism, sin, and guilt.",
        Price: 8.97,
        BookImg: TheScarletLetter,
        Category: "Dramas & Plays",
    },
    {
        BookId: 18,
        BookName: "Admiral Yi Sun-sin",
        Author: "Diamond Sutra Recitation Group",
        Info: "A historical account of Admiral Yi Sun-sin's uninterrupted victories, brilliant tacticsa, and noble spirit that repelled the invasion of 300,000 Japanese troops in 1592 and 1597.",
        Price: 35.99,
        BookImg: ADmiralYiSunSin,
        Category: "History",
    },
    {
        BookId: 19,
        BookName: "An Untold History",
        Author: "Olivette Otele",
        Info: "Conventional wisdom holds that Africans are only a recent presence in Europe. But in African Europeans, renowned historian Olivette Otele debunks this and uncovers a long history of Europeans of African descent. ",
        Price: 18.99,
        BookImg: AfricanEuropeans,
        Category: "History",
    },
    {
        BookId: 20,
        BookName: "Genghis Khan and the Making of the Modern World",
        Author: "Jack Weatherford",
        Info: "The Mongol army led by Genghis Khan subjugated more lands and people in 25 years than the Romans did in 400. In nearly every country the Mongols conquered, they brought an unprecedented rise in cultural communication, expanded trade, and a blossoming of civilization. ",
        Price: 15.99,
        BookImg: GenghisKhan,
        Category: "History",
    },
    {
        BookId: 21,
        BookName: "Meditations",
        Author: "Marcus Aurelius",
        Info: "One of the most significant books ever written by a head of state, the Meditations are a collection of philosophical thoughts by the Emperor Marcus Aurelius (121 - 180 ce). Covering issues such as duty, forgiveness, brotherhood, strength in adversity and the best way to approach life and death, the Meditations have inspired thinkers, poets and politicians since their first publication more than 500 years ago.",
        Price: 9.99,
        BookImg: Meditations,
        Category: "History",
    },
    {
        BookId: 22,
        BookName: "Napoleon: A Life",
        Author: "Andrew Roberts",
        Info: "The story of Napoleon has been written many times. In some versions, he is a military genius, in others a war-obsessed tyrant. Here, historian Adam Zamoyski cuts through the mythology and explains Napoleon against the background of the European Enlightenment and what he was himself seeking to achieve. ",
        Price: 20.99,
        BookImg: NapoleonALife,
        Category: "History",
    },
    {
        BookId: 23,
        BookName: "The Wager",
        Author: "David Grann",
        Info: "On January 28, 1742, a ramshackle vessel of patched-together wood and cloth washed up on the coast of Brazil. Inside were thirty emaciated men, barely alive, and they had an extraordinary tale to tell. They were survivors of His Majesty’s Ship the Wager, a British vessel that had left England in 1740 on a secret mission during an imperial war with Spain. ",
        Price: 16.99,
        BookImg: TheWager,
        Category: "History",
    },
    {
        BookId: 24,
        BookName: "Unruly",
        Author: "David Mitchell",
        Info: "Think you know the kings and queens of England? Think again. In Unruly, David Mitchell explores how early England’s monarchs, while acting as feared rulers firmly guiding their subjects’ destinies, were in reality a bunch of lucky bastards who were mostly as silly and weird in real life as they appear today in their portraits.",
        Price: 13.99,
        BookImg: Unruly,
        Category: "History",
    },
    {
        BookId: 25,
        BookName: "A Little Life",
        Author: "Hanya Yanagihara",
        Info: "When four classmates from a small Massachusetts college move to New York to make their way, they're broke, adrift, and buoyed only by their friendship and ambition. ",
        Price: 11.99,
        BookImg: ALittleLife,
        Category: "Literature",
    },
    {
        BookId: 26,
        BookName: "Fourth Wing",
        Author: "Rebecca Yarros",
        Info: "Twenty-year-old Violet Sorrengail was supposed to enter the Scribe Quadrant, living a quiet life among books and history. Now, the commanding general—also known as her tough-as-talons mother—has ordered Violet to join the hundreds of candidates striving to become the elite of Navarre: dragon riders.",
        Price: 14.59,
        BookImg: FourthWing,
        Category: "Literature",
    },
    {
        BookId: 27,
        BookName: "Haunting Adeline",
        Author: "H.D. Carlton",
        Info: "The Manipulator I can manipulate the emotions of anyone who lets me. I will make you hurt, make you cry, make you laugh and sigh.",
        Price: 17.59,
        BookImg: HauntingAdeline,
        Category: "Literature",
    },
    {
        BookId: 28,
        BookName: "Holly",
        Author: "Stephen King",
        Info: "Holly Gibney, one of Stephen King’s most compelling and ingeniously resourceful characters, returns in this thrilling novel to solve the gruesome truth behind multiple disappearances in a midwestern town.",
        Price: 19.99,
        BookImg: Holly,
        Category: "Literature",
    },
    {
        BookId: 29,
        BookName: "The Exchange",
        Author: "John Grisham",
        Info: "What became of Mitch and Abby McDeere after they exposed the crimes of Memphis law firm Bendini, Lambert & Locke and fled the country?",
        Price: 19.89,
        BookImg: TheExchange,
        Category: "Literature",
    },
    {
        BookId: 30,
        BookName: "The Housemaid",
        Author: "Freida McFadden",
        Info: "“Welcome to the family,” Nina Winchester says as I shake her elegant, manicured hand. I smile politely, gazing around the marble hallway. Working here is my last chance to start fresh. I can pretend to be whoever I like. But I’ll soon learn that the Winchesters’ secrets are far more dangerous than my own… ",
        Price: 9.74,
        BookImg: TheHausemaid,
        Category: "Literature",
    },
    {
        BookId: 31,
        BookName: "The Seven Husbands of Evelyn Hugo",
        Author: "Taylor Jenkins Reid",
        Info: "From the New York Times bestselling author of Daisy Jones & the Six—an entrancing and “wildly addictive journey of a reclusive Hollywood starlet” (PopSugar) as she reflects on her relentless rise to the top and the risks she took, the loves she lost, and the long-held secrets the public could never imagine.",
        Price: 15.99,
        BookImg: TheSevenHusbandsOfEnelynHugo,
        Category: "Literature",
    },
    {
        BookId: 32,
        BookName: "The Odyssey",
        Author: "Homer",
        Info: "Composed at the rosy-fingered dawn of world literature almost three millennia ago, The Odyssey is a poem about violence and the aftermath of war; about wealth, poverty and power; about marriage and family; about travelers, hospitality, and the yearning for home.",
        Price: 11.99,
        BookImg: TheOdyssey,
        Category: "Poetry",
    },
    {
        BookId: 33,
        BookName: "The Tears That Taught Me",
        Author: "Morgan Richard Olivier",
        Info: "The Tears That Taught Me poetry and prose collection guides readers as they dig through the roots of their struggles, truths, faith, and life lessons.",
        Price: 17.59,
        BookImg: TheTearsThatTaughtMe,
        Category: "Poetry",
    },
    {
        BookId: 34,
        BookName: "The Way Forward",
        Author: "Yung Pueblo",
        Info: "In these rapidly changing times, it is more important than ever to know ourselves well and fully, even and especially in the face of turmoil. The Way Forward encourages readers to connect more deeply to their intuition, using it to remain focused and grounded amidst a world in constant flux.",
        Price: 11.99,
        BookImg: TheWayForward,
        Category: "Poetry",
    },
    {
        BookId: 35,
        BookName: "Alfie and Me",
        Author: "Carl Safina",
        Info: "A moving account of raising, then freeing, an orphaned screech owl, whose lasting friendship with the author illuminates humanity’s relationship with the world.",
        Price: 22.99,
        BookImg: AlfieAndMe,
        Category: "Sience & Math",
    },
    {
        BookId: 36,
        BookName: "Knowledge Encyclopedia Human Body!",
        Author: "DK",
        Info: "Explore the human body as you’ve never known before with this ultimate kid’s guide to what goes on under our skin",
        Price: 16.99,
        BookImg: KnowledgeEncyclopedia,
        Category: "Sience & Math",
    },
    {
        BookId: 37,
        BookName: "The 48 Laws of Power",
        Author: "Robert Greene",
        Info: "In the book that People magazine proclaimed “beguiling” and “fascinating,” Robert Greene and Joost Elffers have distilled three thousand years of the history of power into 48 essential laws by drawing from the philosophies of Machiavelli, Sun Tzu, and Carl Von Clausewitz and also from the lives of figures ranging from Henry Kissinger to P.T. Barnum.",
        Price: 17.59,
        BookImg: The48Laws,
        Category: "Sience & Math",
    },
    {
        BookId: 38,
        BookName: "The Boatanist's Sticker Anthology",
        Author: "DK",
        Info: "Get lost in the beauty of the natural world in this captivating collection of botanical stickers.",
        Price: 14.49,
        BookImg: TheBoatanist,
        Category: "Sience & Math",
    },
    {
        BookId: 39,
        BookName: "100 Days of Timed Tests Addition & Subtraction Humble Math",
        Author: "Humble Math",
        Info: "100 days of division problems. Discover the difference a couple minutes of practice can make. These are reproducible practice sheets to help students learn their division facts and recall them with fluidity. This book focuses on digits 0-12. (Answer key included in the back of the book).",
        Price: 12.99,
        BookImg:TimedTests,
        Category: "Sience & Math",
    },
    {
        BookId: 40,
        BookName: "To Infinity and Beyond A Journey of Cosmic Discovery",
        Author: "Neil deGrasse Tyson, Lindsey Nyx Walker",
        Info: "This enlightening illustrated narrative by the world’s most celebrated astrophysicist explains the universe from the solar system to the farthest reaches of space with authority and humor.",
        Price: 18.49,
        BookImg: ToInfinityAndBeyond,
        Category: "Sience & Math",
    },
]